language: android
jdk: oraclejdk8

sudo: required
dist: precise

env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.0
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - extra-android-m2repository
    - extra-android-support
    - extra

before_install:
  - echo yes | android update sdk --all --filter build-tools-$ANDROID_BUILD_TOOLS_VERSION --no-ui --force
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease


deploy:
  provider: releases
  api_key: a71c71fcbfe6525926476957df3ccab55b6d3b8a
  file: app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    tags: true